server:
  port: 80
spring:
  main:
    web-application-type: reactive #senkron değil asenkron işlemler için(aynı anda gerçekleşenler için
  application:
    name: api-gateway-service
  cloud:
    globalcors:
      cors-configurations:
        '[/**]':
          allowed-origins: "*"
          allowed-headers: "*"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:6060
        - id: user-service
          predicates:
            - Path=/user/**
          uri: http://localhost:6062
      default-filters: 
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}
