server:
  port: 80
spring:
  main:
    web-application-type: reactive #senkron değil asenkron işlemler için(aynı anda gerçekleşenler için
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/api/v1/auth/**
          uri: http://localhost:6060
        - id: user-service
          predicates:
            - Path=/api/v1/user/**
          uri: http://localhost:6062
