server:
  port: 6060
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 12345
  datasource:
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/hrDB
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secretKey: ${serkansecretkey}
  issuer: ${serkanissuer}
rabbitmq:
  auth-exchange: auth-exchange
  register-binding-key: register-key
  register-queue: register-queue
  activation-binding-key: activation-key
  activation-queue: queue-activation
  mail-queue: queue-mail
  mail-binding-key: mail-key
