server:
  port: 6062
spring:
  # rabbitmq:
  #   host: localhost
  #   port: 15672
  #   username: user
  #   password: 12345
  datasource:
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/hrUserDB
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secretKey: ${serkansecretkey}
  issuer: ${serkanissuer}
rabbitmq:
  register-queue: register-queue
  activation-queue: queue-activation
  user-exchange: user-exchange
  # mail-queue: queue-mail
  # mail-binding-key: mail-key
  
